Repository Alfresco/acs-deployment, pull requests merged in 2020-10, with the labels that each got.

#429 OPSEXP-511: disable activemq when the value activemq.enabled is set to false within the acs chart
  helm/alfresco-content-services/charts/activemq/templates/deployment-activemq.yaml
  helm/alfresco-content-services/charts/activemq/templates/svc-activemq-broker.yaml
  helm/alfresco-content-services/charts/activemq/templates/svc-activemq-web-console.yaml
  helm/alfresco-content-services/charts/activemq/values.yaml
  helm/alfresco-content-services/requirements.yaml
Labels: PR: reviewed-approved

#432 OPSEXP-574: Update search dependencies
  docker-compose/6.0.N-docker-compose.yml
  docker-compose/6.1.N-docker-compose.yml
  docker-compose/6.2.N-docker-compose.yml
  helm/alfresco-content-services/6.0.N_values.yaml
  helm/alfresco-content-services/6.1.N_values.yaml
  helm/alfresco-content-services/6.2.N_values.yaml
  helm/alfresco-content-services/charts/alfresco-search/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#433 [AAE-3810] fix ADF app when mounted on root context
  helm/alfresco-content-services/requirements.yaml
Labels: PR: reviewed-approved

#435 OPSEXP-562: Update to latest milestone builds
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/requirements.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#438 OPSEXP-562: Updated documentation
  README.md
  docs/docker-compose/README.md
  docs/docker-compose/examples/customisation-guidelines.md
  docs/helm/eks-deployment.md
  docs/helm/examples/customisation-guidelines.md
  docs/helm/examples/email-enabled.md
  docs/helm/examples/search-external-access.md
  docs/helm/examples/with-ai.md
  docs/helm/examples/with-aws-services.md
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/templates/NOTES.txt
  helm/alfresco-content-services/charts/alfresco-search/templates/NOTES.txt
Labels: PR: partially-approved

#439 Release 5.0.0-M1 chart
  .travis.yml
Labels: PR: unreviewed

#440 Bump chart version to M2
  helm/alfresco-content-services/Chart.yaml
Labels: PR: unreviewed

#441 OPSEXP-433: Write Docker for Desktop guide
  .travis.yml
  docs/helm/diagrams/dfd-k8s-enabled.png
  docs/helm/diagrams/dfd-resources.png
  docs/helm/docker-desktop-deployment.md
  docs/helm/eks-deployment.md
  docs/helm/examples/email-enabled.md
  docs/helm/examples/search-external-access.md
  docs/helm/examples/with-ai.md
  docs/helm/examples/with-aws-services.md
  helm/alfresco-content-services/README.md
Labels: PR: partially-approved

#442 OPSEXP-587: Use nfs-client-provisioner from another helm repo
  docs/helm/eks-deployment.md
Labels: PR: reviewed-approved

#446 OPSEXP-586 use shared travis config
  .travis.yml
Labels: PR: reviewed-approved

#447 OPSEXP-592: Fix SOLR issues
  docker-compose/6.0.N-docker-compose.yml
  docs/helm/docker-desktop-deployment.md
  docs/helm/eks-deployment.md
  helm/alfresco-content-services/charts/alfresco-search/templates/deployment.yaml
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
Labels: PR: reviewed-approved

#448 AAE-3945 use shared pre-commit config
  .pre-commit-config.yaml
  README.md
Labels: PR: unreviewed
