Repository Alfresco/acs-deployment, pull requests merged in 2020-08, with the labels that each got.

#398 ATS-811: Updated T-engines to 2.3.3
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#397 Feature/acs-362 dsync helm chart test
  .travis.yml
  helm/alfresco-content-services/charts/activemq/templates/_helpers.tpl
  helm/alfresco-content-services/charts/activemq/templates/svc-activemq-broker.yaml
  helm/alfresco-content-services/charts/activemq/values.yaml
  helm/alfresco-content-services/charts/alfresco-search/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/Chart.yaml
  helm/alfresco-content-services/templates/config-repository.yaml
  test/postman/helm/sync-service-test-helm-collection.json
Labels: PR: unreviewed

#177 REPO-4300: Update Helm Chart to validate if S3 properties are set and…
  helm/alfresco-content-services/templates/config-repository.yaml
  helm/alfresco-content-services/templates/secret-s3.yaml
Labels: PR: unreviewed

#400 ATS-817: Updated T-engines to 2.3.4
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#384 OPSEXP-77: Update and improve documentation - Part 1
  README.md
  docker-compose/README.md
  docs/README.md
  docs/customising-deployment.md
  docs/docker-compose-deployment.md
  docs/docker-compose/README.md
  docs/docker-compose/diagrams/docker-compose-components.png
  docs/docker-compose/diagrams/docker-compose-components.puml
  docs/docker-compose/examples/customisation-guidelines.md
  docs/docker-image-source-locations.md
  docs/helm-chart-releases.md
  docs/helm-deployment-aws_eks.md
  docs/helm-deployment-aws_kops.md
  docs/helm-deployment-minikube.md
  docs/helm-versioning.md
  docs/helm/README.md
  docs/helm/diagrams/eks-attach-policy.png
  docs/helm/diagrams/eks-efs.png
  docs/helm/diagrams/eks-inbound-rules.png
  docs/helm/diagrams/eks-vpc-security-group.png
  docs/helm/diagrams/helm-components-aws-ai.png
  docs/helm/diagrams/helm-components-aws-ai.puml
  docs/helm/diagrams/helm-components-aws.png
  docs/helm/diagrams/helm-components-aws.puml
  docs/helm/diagrams/helm-components-trial.png
  docs/helm/diagrams/helm-components-trial.puml
  docs/helm/diagrams/helm-components.png
  docs/helm/diagrams/helm-components.puml
  docs/helm/docker-desktop-deployment.md
  docs/helm/eks-deployment.md
  docs/helm/examples/acs-deployment-with-custom-metadata-keystore.md
  docs/helm/examples/acs-deployment-with-email-enabled.md
  docs/helm/examples/acs-deployment-with-external-database-kops.md
  docs/helm/examples/acs-deployment-with-s3-connector-kops.md
  docs/helm/examples/ai-reference-values.yaml
  docs/helm/examples/customisation-guidelines.md
  docs/helm/examples/deploy-acs-with-ai.sh
  docs/helm/examples/helm-deployment-acs-with-ai.md
  docs/helm/examples/search-external-access.md
  docs/k8s-pod-security-policies.md
  docs/properties-reference.md
  docs/troubleshooting-helm-deployment.md
  docs/use-cases/acs-deployment-aws-existing-vpc-kops.md
  helm/alfresco-content-services/Chart.yaml
  helm/alfresco-content-services/README.md
Labels: PR: unreviewed

#401 ATS-807: Updated T-router to 1.3.1-RC2
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#402 ATS-808: Bump AIS T-Engine to 1.2.1-RC1
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#404 ATS-820 Update T-router - 1.3.1
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#406 ATS-821 Update AIS to 1.2.1
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#408 SEARCH-2258: Update Search Services to 2.0.0
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#409 OPSEXP-444: Add properties from subsystems to reference page
  docs/properties-reference.md
Labels: PR: partially-approved
