Repository Alfresco/acs-deployment, pull requests merged in 2020-09, with the labels that each got.

#411 ACS-578: Release ACS 7.0.0-M1
  .travis.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#412 Feature/acs 578 test
  helm/alfresco-content-services/templates/config-repository.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#413 OPSEXP-78: Added example to deploy with S3, RDS and MQ
  docs/helm/README.md
  docs/helm/diagrams/eks-db-inbound-rules.png
  docs/helm/diagrams/eks-db-security-group.png
  docs/helm/diagrams/eks-mq-inbound-rules.png
  docs/helm/diagrams/eks-nfs-inbound-rules.png
  docs/helm/diagrams/eks-s3-iam-policy.png
  docs/helm/diagrams/helm-components-aws-ai.png
  docs/helm/diagrams/helm-components-aws.png
  docs/helm/diagrams/helm-components-eks-ai.png
  docs/helm/diagrams/helm-components-eks-ai.puml
  docs/helm/diagrams/helm-components-eks-s3-rds-mq.png
  docs/helm/diagrams/helm-components-eks-s3-rds-mq.puml
  docs/helm/diagrams/helm-components-eks.png
  docs/helm/diagrams/helm-components-eks.puml
  docs/helm/diagrams/helm-components-trial.png
  docs/helm/diagrams/helm-components.png
  docs/helm/diagrams/helm-components.puml
  docs/helm/diagrams/k8s-dashboard.png
  docs/helm/eks-deployment.md
  docs/helm/examples/acs-deployment-with-aws-services.md
  docs/helm/examples/acs-deployment-with-external-database-kops.md
  docs/helm/examples/acs-deployment-with-s3-connector-kops.md
Labels: PR: reviewed-approved

#416 Upgrade Sync Service to 3.3.3.1 after hotfix release
  docker-compose/6.2.N-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/charts/alfresco-sync-service/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
Labels: PR: reviewed-approved

#417 Temporarily disable community build
  .travis.yml
Labels: PR: reviewed-approved

#419 OPSEXP-105: Fix and stabilise build
  .travis.yml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#421 OPSEXP-510: Versioning strategy
  README.md
Labels: PR: partially-approved

#422 OPSEXP-509: Add force tests option
  .travis.yml
Labels: PR: reviewed-approved

#418 Add extra volumes and volumemounts
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#407 MNT-21816 added-installing-amps-examples
  docs/docker-compose/README.md
  docs/docker-compose/examples/installing-amps.md
Labels: PR: reviewed-approved

#424 ATS-825 : Updated T-engines to 2.3.5
  docker-compose/6.2.N-docker-compose.yml
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/6.2.N_values.yaml
  helm/alfresco-content-services/community_values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#426 OPSEXP-134: Customisation guides
  docs/docker-compose/README.md
  docs/docker-compose/examples/customisation-guidelines.md
  docs/docker-compose/examples/installing-amps.md
  docs/helm/README.md
  docs/helm/examples/customisation-guidelines.md
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#428 MNT-21766: Update ACS to v6.2.2.3
  docker-compose/6.2.N-docker-compose.yml
  helm/alfresco-content-services/6.2.N_values.yaml
Labels: PR: reviewed-approved

#427 OPSEXP-555: keystore additions
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/6.0.N_values.yaml
  helm/alfresco-content-services/6.1.N_values.yaml
  helm/alfresco-content-services/6.2.N_values.yaml
  helm/alfresco-content-services/community_values.yaml
  helm/alfresco-content-services/templates/config-repository.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved
