Repository Alfresco/acs-deployment, pull requests merged in 2020-12, with the labels that each got.

#465 AAE-4023 fix add slash to url if missing
  helm/alfresco-content-services/6.0.N_values.yaml
  helm/alfresco-content-services/6.1.N_values.yaml
  helm/alfresco-content-services/6.2.N_values.yaml
  helm/alfresco-content-services/requirements.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#467 Fix typo in README
  docs/helm/docker-desktop-deployment.md
Labels: PR: partially-approved

#468 Minor updates to readme(s) for helm / kubernetes
  docs/helm/docker-desktop-deployment.md
  docs/helm/eks-deployment.md
Labels: PR: partially-approved

#469 SEARCH-2506: Update Search Services to 2.0.1
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/community_values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#470 bump sync service from 3.3.3.1 to 3.4.0-M2
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/6.2.N_values.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
Labels: PR: partially-approved

#475 Bump to ADW 2.0.0
  docker-compose/6.2.N-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/6.2.N_values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#477 OPSEXP-626: Update repo and share to latest images
  README.md
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/community_values.yaml
  helm/alfresco-content-services/requirements.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#478 [release]
  .travis.yml
Labels: PR: unreviewed

#479 Updated chart version to M3
  helm/alfresco-content-services/Chart.yaml
Labels: PR: unreviewed

#480 OPSEXP-664: Allow custom repo debugging configuration to be provided for the ACS helm charts
  helm/alfresco-content-services/6.0.N_values.yaml
  helm/alfresco-content-services/6.1.N_values.yaml
  helm/alfresco-content-services/6.2.N_values.yaml
  helm/alfresco-content-services/templates/config-dev-log4j-properties.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#481 Minor updates to several documentation pages
  CONTRIBUTING.md
  docs/helm/README.md
  docs/helm/diagrams/k8s-lens.png
  docs/helm/docker-desktop-deployment.md
Labels: PR: reviewed-approved
