Repository Alfresco/acs-deployment, pull requests merged in 2020-04, with the labels that each got.

#307 Fixed typo in tika's docker url
  docs/customising-deployment.md
Labels: PR: reviewed-approved

#310 REPO-5079, ATS-707: Use all-in-one T-Engine and fix tests
  docker-compose/docker-compose.yml
  docs/diagrams/docker-compose/docker-compose-components.png
  docs/diagrams/docker-compose/docker-compose-components.puml
  docs/helm-chart-releases.md
  helm/alfresco-content-services/Chart.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#312 SEARCH-2099 Update Search Services to 1.4.2 (RC2)
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#313 ATS-739: Update ACS Deployment to ATS 1.2.0-A2
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#314 SEARCH-2099 Update search to RC3
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#315 ATS-708 / ATS-709: Update to ATS 1.2.0-RC1 & T-engines to 2.2.0
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#318 MNT-20671 - Remove csrf filter for email
  helm/alfresco-content-services/templates/config-repository.yaml
Labels: PR: reviewed-approved

#317 ACS-112: Added ADW url to notes
  helm/alfresco-content-services/templates/NOTES.txt
Labels: PR: partially-approved
