Repository Alfresco/acs-deployment, pull requests merged in 2020-05, with the labels that each got.

#319 ATS-700 ATS-743 Update Transformers
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#320 use ADW 1.5.0
  docker-compose/docker-compose.yml
Labels: PR: partially-approved

#322 update sync service to 3.3.2 and helm chart to 3.0.3
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/requirements.yaml
Labels: PR: partially-approved

#323 ACS-221: Remove specific version from nginx-ingress helm install command
  docs/helm-deployment-aws_kops.md
Labels: PR: partially-approved

#325 ACS-16 add ADW condition to exclude as it was before
  helm/alfresco-content-services/requirements.yaml
Labels: PR: unreviewed

#324 ACS-221 remove ingress from infra
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#327 ACS-221: Pull in latest version of desktop sync chart
  helm/alfresco-content-services/requirements.yaml
Labels: PR: partially-approved

#328 SEARCH-1915 Metadata keystore configuration
  docker-compose/docker-compose.yml
  docs/use-cases/acs-deployment-with-custom-metadata-keystore.md
  helm/alfresco-content-services/templates/config-repository.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/secret-metadata-keystore.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#334 fix helm lint validation
  helm/alfresco-content-services/Chart.yaml
Labels: PR: unreviewed

#212 fixed validation error on resources with helm-2.14/kubectl-1.14
  .editorconfig
  helm/alfresco-content-services/templates/deployment-ai-transformer.yaml
  helm/alfresco-content-services/templates/deployment-filestore.yaml
  helm/alfresco-content-services/templates/deployment-imagemagick.yaml
  helm/alfresco-content-services/templates/deployment-libreoffice.yaml
  helm/alfresco-content-services/templates/deployment-pdfrenderer.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/deployment-share.yaml
  helm/alfresco-content-services/templates/deployment-tika.yaml
  helm/alfresco-content-services/templates/deployment-transform-misc.yaml
  helm/alfresco-content-services/templates/deployment-transform-router.yaml
Labels: PR: unreviewed, triaged

#204 fix: externalize initContainer Docker image repository and tag
  helm/alfresco-content-services/templates/deployment-filestore.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/values.yaml
Labels: triaged

#336 set api back to extensions/v1beta1 to fix build
  helm/alfresco-content-services/templates/deployment-ai-transformer.yaml
  helm/alfresco-content-services/templates/deployment-filestore.yaml
  helm/alfresco-content-services/templates/deployment-imagemagick.yaml
  helm/alfresco-content-services/templates/deployment-libreoffice.yaml
  helm/alfresco-content-services/templates/deployment-pdfrenderer.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/deployment-share.yaml
  helm/alfresco-content-services/templates/deployment-tika.yaml
  helm/alfresco-content-services/templates/deployment-transform-misc.yaml
  helm/alfresco-content-services/templates/deployment-transform-router.yaml
Labels: PR: unreviewed

#337 ACS-273 add missing selectorLabels
  helm/alfresco-content-services/templates/_helpers-ai-transformer.tpl
  helm/alfresco-content-services/templates/_helpers-filestore.tpl
  helm/alfresco-content-services/templates/_helpers-imagemagick.tpl
  helm/alfresco-content-services/templates/_helpers-libreoffice.tpl
  helm/alfresco-content-services/templates/_helpers-pdfrenderer.tpl
  helm/alfresco-content-services/templates/_helpers-repository.tpl
  helm/alfresco-content-services/templates/_helpers-share.tpl
  helm/alfresco-content-services/templates/_helpers-tika.tpl
  helm/alfresco-content-services/templates/_helpers-transform-misc.tpl
  helm/alfresco-content-services/templates/_helpers-transform-router.tpl
  helm/alfresco-content-services/templates/_helpers.tpl
  helm/alfresco-content-services/templates/config-ai-transformer.yaml
  helm/alfresco-content-services/templates/config-email.yaml
  helm/alfresco-content-services/templates/config-filestore.yaml
  helm/alfresco-content-services/templates/config-imagemagick.yaml
  helm/alfresco-content-services/templates/config-libreoffice.yaml
  helm/alfresco-content-services/templates/config-pdfrenderer.yaml
  helm/alfresco-content-services/templates/config-repository.yaml
  helm/alfresco-content-services/templates/config-share.yaml
  helm/alfresco-content-services/templates/config-tika.yaml
  helm/alfresco-content-services/templates/config-transform-misc.yaml
  helm/alfresco-content-services/templates/config-transform-router.yaml
  helm/alfresco-content-services/templates/config-transformer-routes.yaml
  helm/alfresco-content-services/templates/deployment-ai-transformer.yaml
  helm/alfresco-content-services/templates/deployment-filestore.yaml
  helm/alfresco-content-services/templates/deployment-imagemagick.yaml
  helm/alfresco-content-services/templates/deployment-libreoffice.yaml
  helm/alfresco-content-services/templates/deployment-pdfrenderer.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/deployment-share.yaml
  helm/alfresco-content-services/templates/deployment-tika.yaml
  helm/alfresco-content-services/templates/deployment-transform-misc.yaml
  helm/alfresco-content-services/templates/deployment-transform-router.yaml
  helm/alfresco-content-services/templates/ingress-repository.yaml
  helm/alfresco-content-services/templates/ingress-share.yaml
  helm/alfresco-content-services/templates/secret-database.yaml
  helm/alfresco-content-services/templates/secret-mail-password.yaml
  helm/alfresco-content-services/templates/secret-metadata-keystore.yaml
  helm/alfresco-content-services/templates/secret-s3.yaml
  helm/alfresco-content-services/templates/svc-ai-transformer.yaml
  helm/alfresco-content-services/templates/svc-email.yaml
  helm/alfresco-content-services/templates/svc-filestore.yaml
  helm/alfresco-content-services/templates/svc-imagemagick.yaml
  helm/alfresco-content-services/templates/svc-libreoffice.yaml
  helm/alfresco-content-services/templates/svc-pdfrenderer.yaml
  helm/alfresco-content-services/templates/svc-repository.yaml
  helm/alfresco-content-services/templates/svc-share.yaml
  helm/alfresco-content-services/templates/svc-tika.yaml
  helm/alfresco-content-services/templates/svc-transform-misc.yaml
  helm/alfresco-content-services/templates/svc-transform-router.yaml
Labels: PR: unreviewed
