Repository Alfresco/acs-deployment, pull requests merged in 2020-06, with the labels that each got.

#339 ACS-91: Disable network policy setting in helm chart
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#343 ACS-270 Adding Search services into subchart
  .gitignore
  helm/alfresco-content-services/charts/alfresco-search/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/templates/NOTES.txt
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/templates/_helpers.tpl
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/templates/config.yaml
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/templates/deployment.yaml
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/templates/ingress.yaml
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/templates/service.yaml
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/values.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/NOTES.txt
  helm/alfresco-content-services/charts/alfresco-search/templates/_helpers.tpl
  helm/alfresco-content-services/charts/alfresco-search/templates/config.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/deployment.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/ingress.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/pvc.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/secrets.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/service.yaml
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
  helm/alfresco-content-services/requirements.yaml
  helm/alfresco-content-services/templates/NOTES.txt
  helm/alfresco-content-services/templates/Rule_10-network-policy-zeppelin.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#344 ACS-270 Removing and Adding SyncService chart to acs-deployment subchart
  helm/alfresco-content-services/charts/alfresco-sync-service/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/Rule_01-sync-network-policy-database.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/Rule_02-sync-network-policy-activemq.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/Rule_03-sync-network-policy-repository.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/Rule_04-sync-network-policy-syncservice.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/_helpers.tpl
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/config-syncservice.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/deployment-syncservice.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/hpa-syncservice.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/ingress.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/secret-database.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/svc-syncservice.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/requirements.yaml
  helm/alfresco-content-services/templates/NOTES.txt
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#346 ACS-323 remove network policies
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/Rule_01-sync-network-policy-database.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/Rule_02-sync-network-policy-activemq.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/Rule_03-sync-network-policy-repository.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/Rule_04-sync-network-policy-syncservice.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/templates/Rule_01-network-policy-deny-all.yaml
  helm/alfresco-content-services/templates/Rule_02-network-policy-dns.yaml
  helm/alfresco-content-services/templates/Rule_03-network-policy-database.yaml
  helm/alfresco-content-services/templates/Rule_04-network-policy-repository.yaml
  helm/alfresco-content-services/templates/Rule_05-network-policy-search.yaml
  helm/alfresco-content-services/templates/Rule_06-network-policy-share.yaml
  helm/alfresco-content-services/templates/Rule_07-network-policy-transformers.yaml
  helm/alfresco-content-services/templates/Rule_08-network-policy-nginx-ingress.yaml
  helm/alfresco-content-services/templates/Rule_09-network-policy-deny-k8s-dashboard.yaml
  helm/alfresco-content-services/templates/Rule_10-network-policy-zeppelin.yaml
  helm/alfresco-content-services/templates/Rule_11-network-policy-transform-router.yaml
  helm/alfresco-content-services/templates/Rule_12-network-policy-activemq.yaml
  helm/alfresco-content-services/templates/Rule_13-network-policy-filestore.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#345 infra chart removing
  helm/alfresco-content-services/requirements.yaml
  helm/alfresco-content-services/templates/config-ai-transformer.yaml
  helm/alfresco-content-services/templates/config-imagemagick.yaml
  helm/alfresco-content-services/templates/config-libreoffice.yaml
  helm/alfresco-content-services/templates/config-pdfrenderer.yaml
  helm/alfresco-content-services/templates/config-repository.yaml
  helm/alfresco-content-services/templates/config-tika.yaml
  helm/alfresco-content-services/templates/config-transform-misc.yaml
  helm/alfresco-content-services/templates/config-transform-router.yaml
  helm/alfresco-content-services/templates/pvc.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#350 SEARCH-1915: Hide Java Environment values from external process like …
  docker-compose/docker-compose.yml
Labels: PR: reviewed-approved

#351 ATS-776: Update T-Core 1.2.0 to 1.3.0-A2
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#355 ATS-761: Bump to AIS 1.2.0-A1
  helm/alfresco-content-services/ai-reference-values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#358 ATS-784: Bump to ATS 1.3.0-RC1 (targeting ACS 6.2.2)
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#359 ATS-786: Bump to AIS 1.2.0-RC1
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#360 ATS-779: Bump T-Core 2.3.0 for docker-compose only (note: see ACS-358 for k8s)
  docker-compose/docker-compose.yml
Labels: PR: partially-approved

#361 Update README.md
  README.md
Labels: PR: reviewed-approved

#364 bump sync service to 3.3.3-RC2
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/charts/alfresco-sync-service/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
Labels: PR: reviewed-approved

#362 APPS-191: ACS Helm chart issue: JAVA_OPTS from config-share.yaml not …
  helm/alfresco-content-services/templates/config-share.yaml
Labels: PR: partially-approved

#369 ATS-792 Update T-Router to 1.3.0
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#372 Feature/desktopapp 184 update syncservice
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/charts/alfresco-sync-service/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
Labels: PR: reviewed-approved

#374 ATS-774: Bump AI T-Engine to final AIS 1.2.0 (for k8s)
  helm/alfresco-content-services/ai-reference-values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved
