Repository Alfresco/acs-deployment, pull requests merged in 2021-03, with the labels that each got.

#508 Upgrade content repository 7.0.0-A28 (Ent & Com)
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/community_values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#509 REPO-5598 Query Accelerator mount points
  docs/properties-reference.md
  helm/alfresco-content-services/6.1.N_values.yaml
  helm/alfresco-content-services/6.2.N_values.yaml
  helm/alfresco-content-services/community_values.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#510 OPSEXP-805: Increased connection timeout for repo to search communication
  docker-compose/community-docker-compose.yml
Labels: PR: reviewed-approved

#511 Create ELB for TCP services only if email inbound is enabled
  helm/alfresco-content-services/templates/config-email.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/svc-email.yaml
  helm/alfresco-content-services/templates/svc-repository.yaml
Labels: PR: reviewed-approved

#512 OPSEXP-676: Add release tagging
  .travis.yml
Labels: PR: reviewed-approved

#515 Bumb Sync Service to 3.4.0 and helm chart to 3.0.8
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/charts/alfresco-sync-service/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/requirements.yaml
Labels: PR: reviewed-approved

#517 Added information about using multiple docker registry credentials
  docs/helm/docker-desktop-deployment.md
  docs/helm/eks-deployment.md
  docs/helm/examples/customisation-guidelines.md
Labels: PR: unreviewed

#519 ATS-875 Bump AIS to 1.3.0
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#520 OPSEXP-827: ACS Helm deployment is still using Postgres 11 despite being configured with 13
  helm/alfresco-content-services/community_values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#521 Revert "OPSEXP-827: ACS Helm deployment is still using Postgres 11 despite being configured with 13"
  helm/alfresco-content-services/community_values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#522 Upgrade ADW, Share and OOI and revert to Postgres 11.7
  docker-compose/6.2.N-docker-compose.yml
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/6.2.N_values.yaml
  helm/alfresco-content-services/Chart.yaml
  helm/alfresco-content-services/community_values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#523 Update chart version ready for release
  helm/alfresco-content-services/Chart.yaml
Labels: PR: partially-approved

#524 Update versions table
  README.md
Labels: PR: unreviewed

#525 Update version for next development cycle
  helm/alfresco-content-services/Chart.yaml
Labels: PR: unreviewed

#526 Remove the --devel option from docs now we have a released version
  docs/helm/docker-desktop-deployment.md
  docs/helm/eks-deployment.md
  docs/helm/examples/email-enabled.md
  docs/helm/examples/search-external-access.md
  docs/helm/examples/with-ai.md
  docs/helm/examples/with-aws-services.md
  docs/helm/examples/with-ooi.md
Labels: PR: unreviewed

#527 OPSEXP-840 and OPSEXP-842
  README.md
  docker-compose/6.2.N-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/6.2.N_values.yaml
  helm/alfresco-content-services/Chart.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#528 [release]
  README.md
Labels: PR: unreviewed

#531 OPSEXP-852: Update docs to mention escaping semi-colons in database.url
  docs/helm/README.md
  docs/helm/examples/with-aws-services.md
Labels: PR: reviewed-approved

#529 AAE-4349 Use activiti common chart
  .pre-commit-config.yaml
  helm/alfresco-content-services/6.1.N_values.yaml
  helm/alfresco-content-services/6.2.N_values.yaml
  helm/alfresco-content-services/requirements.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed
