Repository Alfresco/acs-deployment, pull requests merged in 2021-12, with the labels that each got.

#630 OPSEXP-1158 update build tools
  .checkov-ignore-list
  .pre-commit-config.yaml
Labels: PR: unreviewed

#629 [ACS-2158] Fix Office to Comprehend transforms via text
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/templates/config-transformer-routes.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#632 [ACS-2158] Changed transformer from libreoffice to TikaAuto in office…
  helm/alfresco-content-services/templates/config-transformer-routes.yaml
Labels: PR: reviewed-approved

#633 Improve docs
  docs/docker-compose/README.md
Labels: PR: partially-approved
