Repository Alfresco/acs-deployment, pull requests merged in 2021-05, with the labels that each got.

#549 Fix product name in diagrams and minor corrections
  docs/docker-compose/diagrams/docker-compose-enterprise.png
  docs/docker-compose/diagrams/docker-compose-enterprise.puml
  docs/helm/diagrams/helm-community.png
  docs/helm/diagrams/helm-community.puml
  docs/helm/diagrams/helm-eks-community.png
  docs/helm/diagrams/helm-eks-community.puml
  docs/helm/diagrams/helm-eks-enterprise.png
  docs/helm/diagrams/helm-eks-enterprise.puml
  docs/helm/diagrams/helm-eks-s3-rds-mq-ai.png
  docs/helm/diagrams/helm-eks-s3-rds-mq-ai.puml
  docs/helm/diagrams/helm-eks-s3-rds-mq-ooi.png
  docs/helm/diagrams/helm-eks-s3-rds-mq-ooi.puml
  docs/helm/diagrams/helm-eks-s3-rds-mq.png
  docs/helm/diagrams/helm-eks-s3-rds-mq.puml
  docs/helm/diagrams/helm-enterprise.png
  docs/helm/diagrams/helm-enterprise.puml
  docs/helm/docker-desktop-deployment.md
  docs/helm/eks-deployment.md
Labels: PR: reviewed-approved

#556 ATS-916 Bump T-Service->1.4.0
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#548 OPSEXP-606: add ssl readme flag
  docs/docker-compose/README.md
Labels: PR: reviewed-approved

#554 Update eks-deployment.md
  docs/helm/eks-deployment.md
Labels: PR: reviewed-approved

#557 Bump Sync Service from 3.3.3.1 to 3.3.4-A2
  docker-compose/6.2.N-docker-compose.yml
  helm/alfresco-content-services/6.2.N_values.yaml
Labels: PR: reviewed-approved

#558 Bump Sync Service from 3.3.4-A2 to 3.3.4-M2
  docker-compose/6.2.N-docker-compose.yml
  helm/alfresco-content-services/6.2.N_values.yaml
Labels: PR: reviewed-approved

#561 Upgrade ADW to 2.2.0
  docker-compose/6.2.N-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/6.2.N_values.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#560 Update Repo and Share to 7.1.0-M1
  .pre-commit-config.yaml
  .travis.yml
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
  docs/docker-compose/README.md
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/community_values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed
