Repository Alfresco/acs-deployment, pull requests merged in 2021-04, with the labels that each got.

#532 ATS-884: Attempting to make t-router work on terraform pipeline
  helm/alfresco-content-services/templates/ai-pipeline-routes.json
  helm/alfresco-content-services/templates/config-transform-router.yaml
Labels: PR: reviewed-approved

#534 ATS-884: Manually reverting as previous revert did not do anything
  helm/alfresco-content-services/templates/ai-pipeline-routes.json
  helm/alfresco-content-services/templates/config-transform-router.yaml
Labels: PR: reviewed-approved

#537 ATS-884: Attempting to make t-router work on terraform pipeline
  helm/alfresco-content-services/templates/ai-pipeline-routes.yaml
  helm/alfresco-content-services/templates/config-transform-router.yaml
Labels: PR: reviewed-approved

#536 OPSEXP-508: Log access
  .travis.yml
Labels: PR: partially-approved

#538 OPSEXP-833: Force deploy and test when running master build
  .travis.yml
Labels: PR: partially-approved

#539 OPSEXP-802: added extra init,side and extra volume posibilities
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/deployment-share.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#540 OPSEXP-832: Improve UI accessibility tests for docker compose
  test/postman/docker-compose/acs-test-docker-compose-collection.json
  test/postman/helm/acs-test-helm-collection.json
Labels: PR: partially-approved

#542 ATS-884: Copied ai-pipeline-routes.json into config-transform-router.yaml
  helm/alfresco-content-services/templates/ai-pipeline-routes.yaml
  helm/alfresco-content-services/templates/config-transform-router.yaml
  helm/alfresco-content-services/templates/config-transformer-routes.yaml
Labels: PR: reviewed-approved

#518 OPSEXP-703: add checkov test and fixes for initial list
  .checkov-ignore-list
  .gitignore
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  .travis.yml
  docs/helm/eks-deployment.md
  helm/alfresco-content-services/6.1.N_values.yaml
  helm/alfresco-content-services/6.2.N_values.yaml
  helm/alfresco-content-services/charts/activemq/templates/deployment-activemq.yaml
  helm/alfresco-content-services/charts/activemq/values.yaml
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/templates/deployment.yaml
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/values.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/deployment.yaml
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/deployment-syncservice.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/community_values.yaml
  helm/alfresco-content-services/templates/deployment-filestore.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/deployment-transform-router.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#544 OPSEXP-435: Automatic chart docs with pre-commit and helm-docs
  .pre-commit-config.yaml
  .travis.yml
  docs/helm/README.md
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/README.md.gotmpl
  helm/alfresco-content-services/charts/activemq/README.md
  helm/alfresco-content-services/charts/activemq/README.md.gotmpl
  helm/alfresco-content-services/charts/activemq/values.yaml
  helm/alfresco-content-services/charts/alfresco-search/README.md
  helm/alfresco-content-services/charts/alfresco-search/README.md.gotmpl
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/README.md
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/README.md.gotmpl
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/values.yaml
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md.gotmpl
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#541 Add ability to configure TLS section
  helm/alfresco-content-services/6.1.N_values.yaml
  helm/alfresco-content-services/6.2.N_values.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/ingress.yaml
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/ingress.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/community_values.yaml
  helm/alfresco-content-services/templates/ingress-ooi-service.yaml
  helm/alfresco-content-services/templates/ingress-repository.yaml
  helm/alfresco-content-services/templates/ingress-share.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#545 Fix pre-commit hook failure
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-search/README.md
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
Labels: PR: reviewed-approved

#546 ATS-884: Add config for ADW AI plugin for AIS
  docs/helm/examples/with-ai.md
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/templates/config-ai-transformer.yaml
  helm/alfresco-content-services/templates/config-transform-router.yaml
  helm/alfresco-content-services/templates/config-transformer-routes.yaml
  helm/alfresco-content-services/templates/deployment-ai-transformer.yaml
  helm/alfresco-content-services/templates/deployment-transform-router.yaml
  helm/alfresco-content-services/templates/svc-ai-transformer.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#547 OPSEXP-827: Allow different versions of Postgres to be used across charts
  helm/alfresco-content-services/6.1.N_values.yaml
  helm/alfresco-content-services/6.2.N_values.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/community_values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#552 ACS-1550: Update docs for Windows environments
  docs/docker-compose/README.md
Labels: PR: reviewed-approved
