Repository Alfresco/acs-deployment, pull requests merged in 2021-02, with the labels that each got.

#492 OPSEXP-755 & OPSEXP-756: Update nginx config
  docker-compose/6.1.N-docker-compose.yml
  docker-compose/6.2.N-docker-compose.yml
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/templates/ingress-share.yaml
  test/postman/docker-compose/acs-test-docker-compose-collection.json
  test/postman/helm/acs-test-helm-collection.json
Labels: PR: partially-approved

#494 ACS-1185 Update activemq images to 5.16.1/ 5.15.14
  docker-compose/6.1.N-docker-compose.yml
  docker-compose/6.2.N-docker-compose.yml
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/charts/activemq/values.yaml
Labels: PR: partially-approved

#496 ATS-862: Release ATS 1.3.2-A2
  docker-compose/6.2.N-docker-compose.yml
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/6.2.N_values.yaml
  helm/alfresco-content-services/community_values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#498 ATS-852 Update alfresco-ai-services to 1.3.0-A1
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#499 Add "Containerized" to the README title [skip ci]
  README.md
Labels: PR: reviewed-approved

#500 Feature/update sync service
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/charts/alfresco-sync-service/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/requirements.yaml
Labels: PR: reviewed-approved

#501 OPSEXP-105: Minor tweak to Community Docker Compose diagram
  docs/docker-compose/diagrams/docker-compose-community.png
  docs/docker-compose/diagrams/docker-compose-community.puml
Labels: PR: partially-approved

#502 ACS-1183 ACS 7 Stacks: PostgreSQL
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
  docs/helm/examples/with-aws-services.md
  helm/alfresco-content-services/community_values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#497 OPSEXP-784: fix dockerhub setup
  .travis.yml
Labels: PR: partially-approved

#503 OPSEXP-787: Remove 6.0.N files and tests
  .travis.yml
  README.md
  docker-compose/6.0.N-docker-compose.yml
  docs/helm/eks-deployment.md
  helm/alfresco-content-services/6.0.N_values.yaml
  test/postman/docker-compose/acs60n-test-docker-compose-collection.json
Labels: PR: reviewed-approved

#505 OPSEXP-714: logstatements causing volume issues
  helm/alfresco-content-services/templates/deployment-repository.yaml
Labels: PR: partially-approved

#504 OPSEXP-763: update prometheus ingress setup
  helm/alfresco-content-services/templates/ingress-repository.yaml
Labels: PR: reviewed-approved

#506 ATS-869 Upgrade ais to 1.3.0-A2
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#507 Upgrade share for Enterprise deployments
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved
