Repository Alfresco/acs-deployment, pull requests merged in 2022-04, with the labels that each got.

#684 OPSEXP-1374: Fix ooi and ms teams service - http 404 error
  helm/alfresco-content-services/templates/ingress-ms-teams-service.yaml
  helm/alfresco-content-services/templates/ingress-ooi-service.yaml
Labels: PR: reviewed-approved

#686 OPSEXP-1378: USe server-snippet to avoid nested location within exact matches
  helm/alfresco-content-services/templates/_helpers-ingress.tpl
  helm/alfresco-content-services/templates/ingress-repository.yaml
  helm/alfresco-content-services/templates/ingress-share.yaml
Labels: PR: reviewed-approved

#689 OPSEXP-1388 Make alfresco-search inclusion configurable
  helm/alfresco-content-services/Chart.yaml
Labels: PR: unreviewed

#690 OPSEXP-1389 Make activemq inclusion configurable
  .pre-commit-config.yaml
  .travis.yml
  helm/alfresco-content-services/Chart.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/activemq/README.md
  helm/alfresco-content-services/charts/alfresco-search/README.md
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/templates/_helpers-activemq.tpl
  helm/alfresco-content-services/templates/config-ai-transformer.yaml
  helm/alfresco-content-services/templates/config-imagemagick.yaml
  helm/alfresco-content-services/templates/config-libreoffice.yaml
  helm/alfresco-content-services/templates/config-pdfrenderer.yaml
  helm/alfresco-content-services/templates/config-tika.yaml
  helm/alfresco-content-services/templates/config-transform-misc.yaml
  helm/alfresco-content-services/templates/config-transform-router.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#694 DESKTOPAPP-991: Bump sync service from 3.6.0 to 3.7.0-A5
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#695 OPSEXP-1221: Fix publish on master branch
  .github/workflows/verify.yml
Labels: PR: reviewed-approved

#696 ACS-2817: Release OOI service 1.1.2
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#697 DESKTOPAPP-962: Bump sync service from 3.7.0-A5 to 3.7.0
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#699 [minor] Remove quotes in pre-commit config for consistency
  .pre-commit-config.yaml
Labels: PR: unreviewed
