Repository Alfresco/acs-deployment, pull requests merged in 2022-09, with the labels that each got.

#762 OPSEXP-1575: move PGDATA away from efs default volume claim
  .github/scripts/helm_install.sh
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#763 DESKTOPAPP-1260: Bump sync service from 3.7.1-A1 to 4.0.0-A3
  docker-compose/7.2.N-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/7.2.N_values.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md.gotmpl
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#764 DESKTOPAPP-1248: Bump sync service from 4.0.0-A3 to 4.0.0-M3
  docker-compose/7.2.N-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/7.2.N_values.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#765 OPSEXP-1575: add postgresql persistence guidance after config change
  README.md
  docs/helm/eks-deployment.md
  docs/helm/storage.md
Labels: PR: reviewed-approved

#768 DESKTOPAPP-1266: Bump Sync Service from 4.0.0-M3 to 3.7.2
  docker-compose/7.2.N-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/7.2.N_values.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#769 OPSEXP-1717 Add Elasticsearch connector to docker-compose
  .pre-commit-config.yaml
  docker-compose/elasticsearch-override-docker-compose.yml
  docs/docker-compose/README.md
Labels: PR: reviewed-approved

#772 DESKTOPAPP-1263: Bump sync service from 3.7.2 to 3.7.3-A1
  docker-compose/7.2.N-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/7.2.N_values.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#767 OPSEXP-1545 Decrease duplication in build scripts for helm charts with github custom actions
  .github/scripts/docker_compose.sh
  .github/scripts/helm_install.sh
  .github/scripts/publish_chart.sh
  .github/workflows/verify.yml
Labels: PR: partially-approved

#774 OPSEXP-1545 Fix workflow for forked PRs
  .github/workflows/verify.yml
Labels: PR: reviewed-approved

#750 OPSEXP-1670 Support existing secret for message broker credentials
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-content-common/templates/_helpers-activemq.tpl
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/liveindexing-config.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/liveindexing-deployment.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/reindexing-config.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/reindexing-job.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/config-syncservice.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/deployment-syncservice.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/templates/config-ai-transformer.yaml
  helm/alfresco-content-services/templates/config-imagemagick.yaml
  helm/alfresco-content-services/templates/config-libreoffice.yaml
  helm/alfresco-content-services/templates/config-pdfrenderer.yaml
  helm/alfresco-content-services/templates/config-repository.yaml
  helm/alfresco-content-services/templates/config-tika.yaml
  helm/alfresco-content-services/templates/config-transform-misc.yaml
  helm/alfresco-content-services/templates/config-transform-router.yaml
  helm/alfresco-content-services/templates/deployment-ai-transformer.yaml
  helm/alfresco-content-services/templates/deployment-imagemagick.yaml
  helm/alfresco-content-services/templates/deployment-libreoffice.yaml
  helm/alfresco-content-services/templates/deployment-pdfrenderer.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/deployment-tika.yaml
  helm/alfresco-content-services/templates/deployment-transform-misc.yaml
  helm/alfresco-content-services/templates/deployment-transform-router.yaml
  helm/alfresco-content-services/templates/secret-message-broker.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#776 OPSEXP-1746: split docker-compose workflows
  .github/workflows/community-compose.yml
  .github/workflows/enterprise-compose.yml
  .github/workflows/verify.yml
  .pre-commit-config.d/compose.yaml
  .pre-commit-config.d/helm.yaml
Labels: PR: unreviewed
