Repository Alfresco/acs-deployment, pull requests merged in 2022-08, with the labels that each got.

#744 OPSEXP-1627 Add support for Elasticsearch credentials
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/README.md
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/_helpers-elasticsearch.tpl
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/liveindexing-config.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/reindexing-config.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/values.yaml
  helm/alfresco-content-services/templates/_helpers-elasticsearch.tpl
  helm/alfresco-content-services/templates/config-repository.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#745 OPSEXP-1627 Document how to deploy with Amazon Opensearch
  docs/helm/examples/with-aws-services.md
Labels: PR: partially-approved

#748 Fix imagePullSecret handling when secret is not set
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/deployment-syncservice.yaml
  helm/alfresco-content-services/templates/deployment-transform-router.yaml
Labels: PR: reviewed-approved

#746 OPSEXP-1630 Bump Pangbourne releases and release 5.3.0-M3
  README.md
  helm/alfresco-content-services/7.2.N_values.yaml
  helm/alfresco-content-services/Chart.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#749 OPSEXP-1657 Fix pull requests coming from forked repos
  .github/workflows/verify.yml
  CONTRIBUTING.md
Labels: PR: partially-approved

#751 OPSEXP-1665 Fixup default values when using embedded elasticsearch
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/templates/_helpers-elasticsearch.tpl
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#754 OPSEXP-1657 Fix pr coming from forked repos
  .github/workflows/verify.yml
Labels: PR: unreviewed

#755 OPSEXP-1656 avoid duplication when declaring imagePullSecrets in helm charts
  helm/alfresco-content-services/charts/alfresco-content-common/templates/_helpers-image-pull-secrets.tpl
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/liveindexing-deployment.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/reindexing-job.yaml
  helm/alfresco-content-services/charts/alfresco-search/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-search/README.md
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/templates/deployment.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/deployment.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/deployment-syncservice.yaml
  helm/alfresco-content-services/templates/deployment-ai-transformer.yaml
  helm/alfresco-content-services/templates/deployment-filestore.yaml
  helm/alfresco-content-services/templates/deployment-imagemagick.yaml
  helm/alfresco-content-services/templates/deployment-libreoffice.yaml
  helm/alfresco-content-services/templates/deployment-ms-teams-service.yaml
  helm/alfresco-content-services/templates/deployment-ooi-service.yaml
  helm/alfresco-content-services/templates/deployment-pdfrenderer.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/deployment-share.yaml
  helm/alfresco-content-services/templates/deployment-tika.yaml
  helm/alfresco-content-services/templates/deployment-transform-misc.yaml
  helm/alfresco-content-services/templates/deployment-transform-router.yaml
Labels: PR: reviewed-approved

#759 OPSEXP-1688: Update docker compose to ACS 7.2.1 and 7.3.0-M2
  README.md
  docker-compose/6.2.N-docker-compose.yml
  docker-compose/7.2.N-docker-compose.yml
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
Labels: PR: reviewed-approved

#760 DESKTOPAPP-1227: Bump sync service from 4.0.0-M2 to 3.7.1-A1
  docker-compose/7.2.N-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/7.2.N_values.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#758 OPSEXP-1695: get rid of solr config leftovers when using search3
  docs/helm/diagrams/helm-eks-s3-rds-mq.png
  docs/helm/diagrams/helm-eks-s3-rds-mq.puml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-content-common/templates/_helpers-search.tpl
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/liveindexing-config.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/_helpers.tpl
  helm/alfresco-content-services/templates/_helpers-elasticsearch.tpl
  helm/alfresco-content-services/templates/config-repository.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#757 OPSEXP-1537-N Remove initcontainers workaround after EFS driver upgrade
  docs/helm/eks-deployment.md
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/templates/deployment-filestore.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#761 OPSEXP-1703 fix spacing in repo config when applying license
  helm/alfresco-content-services/templates/config-repository.yaml
Labels: PR: reviewed-approved
