Repository Alfresco/acs-deployment, pull requests merged in 2022-07, with the labels that each got.

#731 OPSEXP-1574: allow specifying an external ActiveMQ in search enterprise
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-content-common/templates/_helpers-activemq.tpl
  helm/alfresco-content-services/charts/alfresco-content-common/templates/_helpers.tpl
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/README.md
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/liveindexing-config.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/reindexing-config.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/values.yaml
  helm/alfresco-content-services/templates/_helpers-activemq.tpl
  helm/alfresco-content-services/templates/config-imagemagick.yaml
  helm/alfresco-content-services/templates/config-libreoffice.yaml
  helm/alfresco-content-services/templates/config-pdfrenderer.yaml
  helm/alfresco-content-services/templates/config-repository.yaml
  helm/alfresco-content-services/templates/config-tika.yaml
  helm/alfresco-content-services/templates/config-transform-misc.yaml
  helm/alfresco-content-services/templates/config-transform-router.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#732 OPSEXP-1574 Fixup for broken ai-transformer config
  helm/alfresco-content-services/templates/config-ai-transformer.yaml
Labels: PR: unreviewed

#734 ACS-3180: Bump MS 365/OneDrive "sample" (helm chart)
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#736 DESKTOPAPP-1148: Bump sync service from 4.0.0-M1 to 4.0.0-A2
  docker-compose/7.2.N-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/7.2.N_values.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#737 DESKTOPAPP-1136: Bump sync service from 4.0.0-A2 to 4.0.0-M2
  docker-compose/7.2.N-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/7.2.N_values.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#738 ACS-3179, ACS-3243: Bump MS 365/OneDrive and MS Teams "sample" (helm chart)
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#741 ACS-3342 Bump PostgreSQL to the latest 14.x
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
  docs/helm/examples/with-aws-services.md
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#743 OPSEXP-1587: Sync service to use external URL for ActiveMQ
  docs/helm/examples/with-aws-services.md
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/activemq/Chart.yaml
  helm/alfresco-content-services/charts/activemq/README.md
  helm/alfresco-content-services/charts/activemq/templates/_helpers.tpl
  helm/alfresco-content-services/charts/alfresco-content-common/templates/_helpers-activemq.tpl
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/README.md
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/values.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/config-syncservice.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/deployment-syncservice.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/templates/config-repository.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved
