Repository Alfresco/acs-deployment, pull requests merged in 2022-03, with the labels that each got.

#658 ACS-2573 Pick up T-Core 2.5.7-A5, T-Router 1.5.2-A5 and ACS 7.2.0-A27
  .travis.yml
  README.md
  docker-compose/7.1.N-docker-compose.yml
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/7.1.N_values.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#648 OPSEXP-1163: Support shared secret for REPO/SOLR communication
  .checkov/helm_vars.yaml
  .checkov/skip-list
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  .travis.yml
  README.md
  docs/helm/README.md
  helm/alfresco-content-services/6.1.N_values.yaml
  helm/alfresco-content-services/6.2.N_values.yaml
  helm/alfresco-content-services/7.0.N_values.yaml
  helm/alfresco-content-services/7.1.N_values.yaml
  helm/alfresco-content-services/Chart.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/activemq/README.md
  helm/alfresco-content-services/charts/alfresco-search/README.md
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/README.md
  helm/alfresco-content-services/charts/alfresco-search/templates/_helpers.tpl
  helm/alfresco-content-services/charts/alfresco-search/templates/config.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/deployment.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/solr-shared-secret.yaml
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/templates/config-repository.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/secret-solr-tracking.yml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#662 Pick up T-Core 2.5.7-A9, T-Router 1.5.2-A9, Search 2.0.3-RC3 & ACS 7.2.0-A28
  README.md
  docker-compose/7.1.N-docker-compose.yml
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/7.1.N_values.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-search/README.md
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#665 ACS-2307 Update SS/IE to 2.0.3-RC4
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-search/README.md
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#664 DESKTOPAPP-897: Bump sync service from 3.5.0 to 3.6.0-A2
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#667 Pick up GA versions of T-Core 2.5.7 & T-Router 1.5.2
  README.md
  docker-compose/7.1.N-docker-compose.yml
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/7.1.N_values.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#668 Acs 2670 pickup ais 1.4.2 a11
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#669 ACS-2307 Update IE/SS to 2.0.3-RC5
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-search/README.md
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#666 OPSEXP-1318 Fix YAML parse error when sharedsecret contains special characters
  helm/alfresco-content-services/charts/alfresco-search/README.md
  helm/alfresco-content-services/charts/alfresco-search/templates/deployment.yaml
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
Labels: PR: unreviewed

#670 ACS-2307 Update IE/SS to 2.0.3
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-search/README.md
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#671 DESKTOPAPP-900: Bump sync service from 3.6.0-A2 to 3.6.0
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#672 OPSEXP-1339 Support k8s 1.22
  .gitignore
  .travis.yml
  helm/alfresco-content-services/Chart.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-search/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-search/README.md
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/README.md
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/templates/ingress.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/ingress.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/ingress.yaml
  helm/alfresco-content-services/templates/ingress-ms-teams-service.yaml
  helm/alfresco-content-services/templates/ingress-ooi-service.yaml
  helm/alfresco-content-services/templates/ingress-repository.yaml
  helm/alfresco-content-services/templates/ingress-share.yaml
Labels: PR: unreviewed

#676 OPSEXP-1343: Remove builds for the now unsupported 6.1
  .travis.yml
  README.md
  docker-compose/6.1.N-docker-compose.yml
  docs/docker-compose/README.md
  docs/helm/eks-deployment.md
  helm/alfresco-content-services/6.1.N_values.yaml
Labels: PR: partially-approved

#674 OPSEXP-1199 Adds and documents a license installation mechanism
  .travis.yml
  docs/helm/README.md
  docs/helm/examples/alf_license.md
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/templates/config-repository.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#678 ACS-2671 Pick up GA versions of Repo and Share in 7.2.0
  README.md
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#661 OPSEXP-1035 Updated ActiveMQ to 5.16.4
  docker-compose/6.1.N-docker-compose.yml
  docker-compose/6.2.N-docker-compose.yml
  docker-compose/7.0.N-docker-compose.yml
  docker-compose/7.1.N-docker-compose.yml
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/Chart.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/activemq/Chart.yaml
  helm/alfresco-content-services/charts/activemq/README.md
  helm/alfresco-content-services/charts/activemq/values.yaml
  helm/alfresco-content-services/charts/alfresco-search/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/Chart.yaml
Labels: PR: unreviewed

#679 OPSEXP-1343 Remove 6.1.x config files
  README.md
  docker-compose/6.1.N-docker-compose.yml
  helm/alfresco-content-services/6.1.N_values.yaml
Labels: PR: unreviewed

#680 ACS-2671 Update alfresco-ai-docker-engine to 1.4.2
  .pre-commit-config.yaml
  .travis.yml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/activemq/README.md
  helm/alfresco-content-services/charts/activemq/values.yaml
  helm/alfresco-content-services/charts/alfresco-search/README.md
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#673 OPSEXP-933: Add node selector for deployments on ACS Helm Chart
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/activemq/README.md
  helm/alfresco-content-services/charts/activemq/templates/deployment-activemq.yaml
  helm/alfresco-content-services/charts/activemq/values.yaml
  helm/alfresco-content-services/charts/alfresco-search/README.md
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/README.md
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/templates/deployment.yaml
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/values.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/deployment.yaml
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/deployment-syncservice.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/templates/deployment-ai-transformer.yaml
  helm/alfresco-content-services/templates/deployment-filestore.yaml
  helm/alfresco-content-services/templates/deployment-imagemagick.yaml
  helm/alfresco-content-services/templates/deployment-libreoffice.yaml
  helm/alfresco-content-services/templates/deployment-ms-teams-service.yaml
  helm/alfresco-content-services/templates/deployment-ooi-service.yaml
  helm/alfresco-content-services/templates/deployment-pdfrenderer.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/deployment-share.yaml
  helm/alfresco-content-services/templates/deployment-tika.yaml
  helm/alfresco-content-services/templates/deployment-transform-misc.yaml
  helm/alfresco-content-services/templates/deployment-transform-router.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#681 OPSEXP-1226: Alfresco Control Center in ACS Deployment - docker-compose
  docker-compose/docker-compose.yml
  docs/docker-compose/README.md
Labels: PR: partially-approved

#682 OPSEXP-1339 Update ingress-nginx to 4.x for k8s 1.22
  .travis.yml
  docs/helm/docker-desktop-deployment.md
  docs/helm/eks-deployment.md
  helm/alfresco-content-services/Chart.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/templates/ingress-repository.yaml
  helm/alfresco-content-services/templates/ingress-share.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#683 OPSEXP-1348 use ACS_VERSION for build stages
  .gitignore
  .pre-commit-config.yaml
  .travis.yml
Labels: PR: unreviewed
