Repository Alfresco/acs-deployment, pull requests merged in 2022-02, with the labels that each got.

#647 DESKTOPAPP-847: Bump Sync Service from 3.5.0-A4 to 3.5.0
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#650 OPSEXP-1214: Release acs-deployment 5.2.0-M2
  .pre-commit-config.yaml
  README.md
  docker-compose/7.1.N-docker-compose.yml
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
  docs/docker-compose/README.md
  helm/alfresco-content-services/6.2.N_values.yaml
  helm/alfresco-content-services/7.0.N_values.yaml
  helm/alfresco-content-services/7.1.N_values.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#655 [ACS-2564] update docker-compose and community-docker-compose to use solr with secureComms=secret
  docker-compose/community-docker-compose.yml
  docker-compose/docker-compose.yml
Labels: PR: unreviewed

#654 ACS-2542 Add 'X-Alfresco-Search-Secret' header to probe requests
  helm/alfresco-content-services/charts/alfresco-search/templates/deployment.yaml
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
Labels: PR: unreviewed
