Repository Alfresco/acs-deployment, pull requests merged in 2022-10, with the labels that each got.

#779 move checkov config to a default location
  .checkov.yml
  .github/workflows/community-compose.yml
  .github/workflows/enterprise-compose.yml
  .pre-commit-config.d/docker.yaml
  .pre-commit-config.d/helm.yaml
  .pre-commit-config.yaml
Labels: PR: reviewed-approved

#781 More clear elasticsearch host docs
  docs/helm/examples/with-aws-services.md
Labels: PR: reviewed-approved

#778 OPSEXP-1746: refactoring for helm splitted charts and community support
  .github/actions/charts-as-json/action.yml
  .github/actions/use-local-deps/action.yml
  .github/actions/use-local-deps/local-deps.sh
  .github/workflows/community-compose.yml
  .github/workflows/enterprise-compose.yml
  .github/workflows/helm-community.yml
  .github/workflows/helm-enterprise.yml
  .github/workflows/verify.yml
  helm/alfresco-common/Chart.yaml
  helm/alfresco-content-services/tests/activemq_test.yaml
  helm/alfresco-content-services/tests/alfresco-common_test.yaml
  helm/alfresco-content-services/tests/externalBroker_test.yaml
  test/community-integration-test-values.yaml
  test/kind-ingress-enabled-cluster.yaml
  test/postman/helm/acs-test-helm-collection.json
Labels: PR: reviewed-approved

#783 OPSEXP-1766: fix ES protocol Issue
  helm/alfresco-content-services/templates/_helpers-elasticsearch.tpl
  helm/alfresco-content-services/templates/config-repository.yaml
  helm/alfresco-content-services/tests/search_test.yaml
Labels: PR: partially-approved

#784 OPSEXP-1766 Fixup helm deployment error
  helm/alfresco-content-services/templates/config-repository.yaml
Labels: PR: partially-approved

#782 OPSEXP-1746: update workflow badges
  .github/workflows/docker-compose-community.yml
  .github/workflows/docker-compose-enterprise.yml
  .github/workflows/helm-community.yml
  .github/workflows/helm-enterprise.yml
  README.md
Labels: PR: partially-approved

#785 Bump sync service from 3.7.3-A1 to 3.8.0-A1
  docker-compose/7.2.N-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/7.2.N_values.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#786 OPSEXP-1777 Proper cleanup for helm enteprise jobs
  .github/workflows/helm-enterprise.yml
Labels: PR: reviewed-approved

#789 Fixup workflow badges
  README.md
Labels: PR: reviewed-approved

#788 OPSEXP-1793 Dedicated pre-commit workflow to avoid duplicated configs
  .github/workflows/docker-compose-community.yml
  .github/workflows/docker-compose-enterprise.yml
  .github/workflows/helm-community.yml
  .github/workflows/helm-enterprise.yml
  .github/workflows/pre-commit-compose.yml
  .github/workflows/pre-commit-helm.yml
  .pre-commit-config.d/docker.yaml
  .pre-commit-config.d/helm.yaml
  .pre-commit-config.yaml
Labels: PR: partially-approved

#787 Make base64 commands in docs platform independent
  docs/helm/examples/alf_license.md
  docs/helm/examples/search-external-access.md
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-search/README.md
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#790 Limit concurrency in helm enterprise jobs
  .github/workflows/helm-enterprise.yml
Labels: PR: reviewed-approved

#791 Add basic dependabot for github actions
  .github/dependabot.yml
Labels: PR: unreviewed

#793 DESKTOPAPP-1310: Bump sync service from 3.8.0-A1 to 3.8.0
  docker-compose/7.2.N-docker-compose.yml
  docker-compose/docker-compose.yml
  helm/alfresco-content-services/7.2.N_values.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#795 OPSEXP-1798 Fix elasticsearch reindexing job database credentials
  .github/workflows/helm-enterprise.yml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/reindexing-job.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/tests/reindexing_test.yaml
  helm/alfresco-content-services/tests/activemq_test.yaml
  helm/alfresco-content-services/tests/alfresco-common_test.yaml
  helm/alfresco-content-services/tests/search_test.yaml
  helm/alfresco-content-services/tests/values/externalBroker_values.yaml
  helm/alfresco-content-services/tests/values/test_values.yaml
Labels: PR: partially-approved

#794 skip helm enterprise for dependabot
  .github/workflows/helm-enterprise.yml
Labels: PR: partially-approved

#798 wait for nginx-ingress during community workflow
  .github/workflows/helm-community.yml
Labels: PR: reviewed-approved

#796 OPSEXP-1811: fix alf-ES config
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/liveindexing-config.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/reindexing-config.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/tests/liveindexing_test.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/tests/values/external.yaml
  helm/alfresco-content-services/tests/activemq_test.yaml
  helm/alfresco-content-services/tests/alfresco-common_test.yaml
  helm/alfresco-content-services/tests/search_test.yaml
Labels: PR: partially-approved

#799 OPSEXP-1772 Deprecation of GHA set-output command
  .github/actions/charts-as-json/action.yml
  .github/workflows/helm-enterprise.yml
Labels: PR: reviewed-approved
