Repository Alfresco/acs-deployment, pull requests merged in 2022-12, with the labels that each got.

#816 OPSEXP-1583: document approach to persistent storage
  docs/helm/diagrams/charts-storage-persistence.png
  docs/helm/diagrams/charts-storage-persistence.puml
  docs/helm/storage.md
Labels: PR: reviewed-approved

#822 Updated the documentation with the configuration for Rancher Desktop
  README.md
  docs/helm/docker-desktop-deployment.md
Labels: PR: reviewed-approved

#827 OPSEXP-1890 Retiring ACS 6.2
  .github/workflows/docker-compose-enterprise.yml
  .pre-commit-config.yaml
  README.md
  docker-compose/6.2.N-docker-compose.yml
  docs/docker-compose/examples/customisation-guidelines.md
  docs/helm/examples/email-enabled.md
  docs/properties-reference.md
  helm/alfresco-content-services/6.2.N_values.yaml
Labels: PR: partially-approved

#823 Opsexp-1578 Activemq should not using alfresco-volume-claim by default
  helm/alfresco-content-services/charts/activemq/Chart.yaml
  helm/alfresco-content-services/charts/activemq/README.md
  helm/alfresco-content-services/charts/activemq/templates/deployment-activemq.yaml
  helm/alfresco-content-services/charts/activemq/templates/pvc-activemq.yaml
  helm/alfresco-content-services/charts/activemq/tests/pv_activemq_test.yaml
  helm/alfresco-content-services/charts/activemq/values.yaml
Labels: PR: partially-approved

#821 OPSEXP-1584 Repository Volume Without Default Alfresco Volume Claim
  .github/workflows/docker-compose-community.yml
  .github/workflows/docker-compose-enterprise.yml
  .github/workflows/helm-community.yml
  .github/workflows/helm-enterprise.yml
  .github/workflows/helm-release.yml
  .github/workflows/pre-commit-compose.yml
  .github/workflows/pre-commit-helm-docs.yml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/community_values.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/pvc.yaml
  helm/alfresco-content-services/tests/pv-repository_test.yaml
  helm/alfresco-content-services/tests/pv-transform_test.yaml
  helm/alfresco-content-services/values.yaml
  test/community-integration-test-values.yaml
Labels: PR: partially-approved

#829 OPSEXP-1901 Document manual release steps - waiting for automation
  README.md
Labels: PR: partially-approved

#828 OPSEXP-1875 Prepare for the next iteration
  helm/alfresco-common/Chart.yaml
  helm/alfresco-content-services/Chart.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/activemq/Chart.yaml
  helm/alfresco-content-services/charts/activemq/README.md
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/README.md
  helm/alfresco-content-services/charts/alfresco-search/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-search/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
Labels: PR: unreviewed
