Repository Alfresco/acs-deployment, pull requests merged in 2023-01, with the labels that each got.

#834 OPSEXP-1915: use ephemeral volumes when persistence is disabled.
  docs/helm/diagrams/charts-storage-persistence.png
  docs/helm/diagrams/charts-storage-persistence.puml
  helm/alfresco-common/templates/_helpers-persistence.tpl
  helm/alfresco-content-services/charts/activemq/templates/deployment-activemq.yaml
  helm/alfresco-content-services/charts/activemq/tests/pv_activemq_test.yaml
  helm/alfresco-content-services/templates/deployment-filestore.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/tests/pv-repository_test.yaml
  helm/alfresco-content-services/tests/pv-transform_test.yaml
Labels: PR: partially-approved

#838 OPSEXP-1761: Bump Alfresco/alfresco-build-tools from 1.26.0 to 1.28.0
  .github/workflows/docker-compose-community.yml
  .github/workflows/docker-compose-enterprise.yml
  .github/workflows/helm-community.yml
  .github/workflows/helm-enterprise.yml
  .github/workflows/helm-release.yml
  .github/workflows/pre-commit-compose.yml
  .github/workflows/pre-commit-helm-docs.yml
Labels: PR: reviewed-approved

#839 OPSEXP-1651 support existing secret for search ingress
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-search/README.md
  helm/alfresco-content-services/charts/alfresco-search/templates/ingress.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/secrets.yaml
  helm/alfresco-content-services/charts/alfresco-search/tests/ingress_test.yaml
  helm/alfresco-content-services/charts/alfresco-search/tests/secret_test.yaml
  helm/alfresco-content-services/charts/alfresco-search/tests/values/ingress.yaml
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#831 OPSEXP-820: do not skip CKV_K8S_23
  .checkov.yml
  .checkov/helm_vars.yaml
  .github/actions/use-local-deps/local-deps.sh
  helm/alfresco-common/templates/_helpers-security.yaml
  helm/alfresco-content-services/Chart.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/activemq/Chart.yaml
  helm/alfresco-content-services/charts/activemq/README.md
  helm/alfresco-content-services/charts/activemq/templates/deployment-activemq.yaml
  helm/alfresco-content-services/charts/activemq/values.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/README.md
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/liveindexing-deployment.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/reindexing-job.yaml
  helm/alfresco-content-services/charts/alfresco-search/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-search/README.md
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/Chart.yaml
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/README.md
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/templates/deployment.yaml
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/values.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/deployment.yaml
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/deployment-syncservice.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/templates/deployment-ai-transformer.yaml
  helm/alfresco-content-services/templates/deployment-filestore.yaml
  helm/alfresco-content-services/templates/deployment-imagemagick.yaml
  helm/alfresco-content-services/templates/deployment-libreoffice.yaml
  helm/alfresco-content-services/templates/deployment-ms-teams-service.yaml
  helm/alfresco-content-services/templates/deployment-ooi-service.yaml
  helm/alfresco-content-services/templates/deployment-pdfrenderer.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/deployment-share.yaml
  helm/alfresco-content-services/templates/deployment-tika.yaml
  helm/alfresco-content-services/templates/deployment-transform-misc.yaml
  helm/alfresco-content-services/templates/deployment-transform-router.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#837 OPSEXP-1651 Use secret to configure elasticsearch credentials
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/README.md
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/_helpers-elasticsearch.tpl
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/liveindexing-deployment.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/reindexing-job.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/secret-elasticsearch.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/tests/liveindexing_test.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/tests/reindexing_test.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/tests/secret-elasticsearch_test.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/values.yaml
Labels: PR: partially-approved

#840 OPSEXP-1651 Use existing secret to configure ACS postgres credentials
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/README.md
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/reindexing-job.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/tests/reindexing_test.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/values.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/secret-database.yaml
  helm/alfresco-content-services/tests/secret-database_test.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#842 OPSEXP-1651 Use existing secret to configure repo admin password
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/templates/config-repository.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/secret-repository.yaml
  helm/alfresco-content-services/tests/activemq_test.yaml
  helm/alfresco-content-services/tests/deployment-repository_test.yaml
  helm/alfresco-content-services/tests/pv-repository_test.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#833 OPSEXP-1651 Use existing secret to configure activemq credentials in embedded chart
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/activemq/Chart.yaml
  helm/alfresco-content-services/charts/activemq/README.md
  helm/alfresco-content-services/charts/activemq/README.md.gotmpl
  helm/alfresco-content-services/charts/activemq/templates/deployment-activemq.yaml
  helm/alfresco-content-services/charts/activemq/tests/deployment-activemq_test.yaml
  helm/alfresco-content-services/charts/activemq/values.yaml
  helm/alfresco-content-services/templates/secret-message-broker.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#846 Fix deprecation warning for helm build action
  .github/workflows/helm-community.yml
Labels: PR: partially-approved

#848 OPSEXP-1651 Document the new security features
  docs/helm/README.md
  docs/helm/security.md
Labels: PR: partially-approved

#845 OPSEXP-1651 Support existing secret for mail password
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/secret-mail-password.yaml
  helm/alfresco-content-services/tests/deployment-repository_test.yaml
  helm/alfresco-content-services/tests/secret-mail-password_test.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: partially-approved

#844 OPSEXP-1651 Support existing secret for s3 connector
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/templates/config-repository.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/secret-s3.yaml
  helm/alfresco-content-services/tests/deployment-repository_test.yaml
  helm/alfresco-content-services/tests/secret-s3_test.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: unreviewed

#851 OPSEXP-1925: clarify EFS usage and implications of removing it
  docs/helm/examples/with-aws-services.md
Labels: PR: partially-approved

#850 OPSEXP-1879 Enforce markdown linting
  .pre-commit-config.yaml
  docs/docker-compose/README.md
  docs/helm/eks-deployment.md
  docs/helm/examples/alf_license.md
  docs/helm/examples/with-ms-teams.md
  docs/helm/examples/with-ooi.md
  docs/helm/storage.md
Labels: PR: merged

#852 OPSEXP-1937: set max boolean clause for ES
  docs/helm/examples/with-aws-services.md
Labels: PR: partially-approved

#843 update doc for external search setup
  docs/helm/README.md
  docs/helm/examples/search-external-access.md
  docs/helm/examples/search-services.md
Labels: PR: partially-approved

#853 OPSEXP-1826 Have a dedicated value to toggle outbound email configuration
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/templates/config-repository.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/secret-mail-password.yaml
  helm/alfresco-content-services/tests/config-repository_test.yaml
  helm/alfresco-content-services/tests/deployment-repository_test.yaml
  helm/alfresco-content-services/tests/secret-mail-password_test.yaml
  helm/alfresco-content-services/values.yaml
Labels: PR: reviewed-approved

#857 OPSEXP-1942 Fix duplicated key in share configmap
  helm/alfresco-content-services/templates/config-share.yaml
  helm/alfresco-content-services/tests/config-share_test.yaml
Labels: PR: partially-approved

#855 OPSEXP-139 Document custom images overrides
  docs/helm/README.md
  docs/helm/docker-desktop-deployment.md
  docs/helm/eks-deployment.md
  docs/helm/registry-authentication.md
Labels: PR: unreviewed

#858 OPSEXP-1942 Add helm-template-yamllint action
  .github/workflows/helm-community.yml
  helm/alfresco-content-services/templates/deployment-filestore.yaml
Labels: PR: unreviewed

#854 OPSEXP-1940: add solr/repo tracking secret
  docs/helm/docker-desktop-deployment.md
  docs/helm/eks-deployment.md
  docs/helm/examples/email-enabled.md
  docs/helm/examples/search-services.md
  docs/helm/examples/with-ai.md
  docs/helm/examples/with-aws-services.md
  docs/helm/examples/with-ms-teams.md
  docs/helm/examples/with-ooi.md
Labels: PR: reviewed-approved

#861 OPSEXP-1963: add back volumes mounts and add tests
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/tests/deployment-repository_test.yaml
Labels: PR: partially-approved

#862 OPSEXP-1931 Create a dedicated workflow for helm unit tests
  .github/workflows/helm-community.yml
  .github/workflows/helm-static-checks.yml
Labels: PR: reviewed-approved

#859 OPSEXP-819 Have cpu resources set everywhere
  .checkov.yml
  .github/workflows/helm-community.yml
  .pre-commit-config.yaml
  helm/alfresco-content-services/README.md
  helm/alfresco-content-services/charts/activemq/README.md
  helm/alfresco-content-services/charts/activemq/templates/deployment-activemq.yaml
  helm/alfresco-content-services/charts/activemq/tests/deployment-activemq_test.yaml
  helm/alfresco-content-services/charts/activemq/values.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/README.md
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/liveindexing-deployment.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/reindexing-job.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/tests/liveindexing-deployment_test.yaml
  helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/values.yaml
  helm/alfresco-content-services/charts/alfresco-search/README.md
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/README.md
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/templates/deployment.yaml
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/tests/deployment_test.yaml
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/tests/values/test.yaml
  helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/values.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/deployment.yaml
  helm/alfresco-content-services/charts/alfresco-search/tests/deployment_test.yaml
  helm/alfresco-content-services/charts/alfresco-search/values.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/README.md
  helm/alfresco-content-services/charts/alfresco-sync-service/templates/deployment-syncservice.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/tests/deployment-syncservice_test.yaml
  helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
  helm/alfresco-content-services/templates/deployment-ai-transformer.yaml
  helm/alfresco-content-services/templates/deployment-filestore.yaml
  helm/alfresco-content-services/templates/deployment-imagemagick.yaml
  helm/alfresco-content-services/templates/deployment-libreoffice.yaml
  helm/alfresco-content-services/templates/deployment-ms-teams-service.yaml
  helm/alfresco-content-services/templates/deployment-ooi-service.yaml
  helm/alfresco-content-services/templates/deployment-pdfrenderer.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/deployment-share.yaml
  helm/alfresco-content-services/templates/deployment-tika.yaml
  helm/alfresco-content-services/templates/deployment-transform-misc.yaml
  helm/alfresco-content-services/templates/deployment-transform-router.yaml
  helm/alfresco-content-services/tests/deployment-repository_test.yaml
  helm/alfresco-content-services/values.yaml
  test/community-integration-test-values.yaml
Labels: PR: reviewed-approved

#863 OPSEXP-1938 Avoid using JAVA_TOOL_OPTIONS in repository for setting solr secret
  .github/workflows/helm-enterprise.yml
  helm/alfresco-content-services/charts/alfresco-search/templates/config.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/deployment.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/ingress.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/secret-ingress.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/secret-solr-jtoolopt.yaml
  helm/alfresco-content-services/charts/alfresco-search/templates/secret-solr-jtoolopt.yml
  helm/alfresco-content-services/charts/alfresco-search/tests/config_test.yaml
  helm/alfresco-content-services/charts/alfresco-search/tests/deployment_test.yaml
  helm/alfresco-content-services/charts/alfresco-search/tests/ingress_test.yaml
  helm/alfresco-content-services/charts/alfresco-search/tests/secret-ingress_test.yaml
  helm/alfresco-content-services/charts/alfresco-search/tests/secret-solr-jtoolopt_test.yaml
  helm/alfresco-content-services/templates/deployment-repository.yaml
  helm/alfresco-content-services/templates/secret-repo-jtoolopt.yaml
  helm/alfresco-content-services/templates/secret-repository-properties.yaml
  helm/alfresco-content-services/tests/activemq_test.yaml
  helm/alfresco-content-services/tests/deployment-repository_test.yaml
  helm/alfresco-content-services/tests/ingress-repository_test.yaml
  helm/alfresco-content-services/tests/secret-repository-properties_test.yaml
Labels: PR: reviewed-approved
